fix: broken warnings in lint and test workflow

diff --git a/.github/workflows/python-lint-and-test.yml b/.github/workflows/python-lint-and-test.yml
--- a/.github/workflows/python-lint-and-test.yml
+++ b/.github/workflows/python-lint-and-test.yml
@@ -36,23 +36,13 @@ jobs:
         run: poetry install
 
       - name: Lint code
-        continue-on-error: true
-        run: poetry run flake8 .
-
-      - name: Warn if linting fails
-        if: ${{ failure() }}
-        run: echo "::warning ::Linting failed! Read logs for more detail."
+        run: poetry run flake8 . || echo "::warning ::Linting failed! Read logs for more detail."
 
       - name: Check dependency safety
-        continue-on-error: true
         run: |
-          poetry run poetry check
-          poetry run pip check
-          poetry run safety check --full-report
-
-      - name: Warn if depency safety checks fail
-        if: ${{ failure() }}
-        run: echo "::warning ::Dependency safety checks failed! Read logs for more detail."
+          poetry run poetry check || echo "::warning ::Dependency safety checks failed! Read logs for more detail."
+          poetry run pip check || echo "::warning ::Dependency safety checks failed! Read logs for more detail."
+          poetry run safety check --full-report || echo "::warning ::Dependency safety checks failed! Read logs for more detail."
 
       - name: Create SQLite db from .sql file
         run: grep -Ev "START TRANSACTION;|COMMIT;" depositaire.sql | sqlite3 depositaire.sqlite
